# Generated by Django 3.1 on 2020-08-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tipo evento',
                'verbose_name_plural': 'Tipos de eventos',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='descripcion_cat',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.categoria'),
        ),
    ]
